## Random Numbers in NumPy

In [1]:
from numpy import random

x = random.randint(100)

print(x)

5


In [2]:

x = random.rand()

print(x)

0.9725859784814452


In [3]:
x=random.randint(100, size=(5))

print(x)

[37  9 86 87 29]


In [4]:
x = random.randint(100, size=(3, 5))

print(x)

[[27 76 21 25 18]
 [50 99 28 49 13]
 [23 15 89 92 85]]


In [5]:
x = random.rand(5)

print(x)

[0.60265756 0.33732357 0.92994824 0.68022806 0.95950648]


In [6]:

x = random.rand(3, 5)

print(x)

[[0.67637116 0.93038675 0.52186707 0.16958063 0.31269156]
 [0.77720647 0.3819033  0.85131327 0.22933216 0.1073762 ]
 [0.82880906 0.76823522 0.64539159 0.86272028 0.611449  ]]


In [7]:
x = random.choice([3, 5, 7, 9])

print(x)

5


In [8]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 9 3 9]
 [3 5 9 7 7]
 [9 9 5 9 7]]
